Try to Fix NPE when running tests on travis by moving test resources to src/test/resources
NPE was:
java.lang.NullPointerException: in is null
at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:100)
at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:79)
at
com.sarod.equinox.config.builder.BundleInfoLoader.loadManifest(BundleInfoLoader.java:72)